config/routes.rb
Rails.application.routes.draw do

  root "static#home"

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: "user"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :books do
    resources :reviews, only: [:index, :new, :create]
    resources :checkouts, only: [:create, :update]
  end

  resources :checkouts, only: [:index]

  scope '/admin' do
    resources :reviews, only: [:index]
  end

  resources :reviews, only: [:show, :edit, :update, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :checkouts, foreign_key: :borrower_id
  has_many :borrowed_books, through: :checkouts, source: :borrowed_book
  has_many :reviews, foreign_key: :reviewer_id
  has_many :reviewed_books, through: :reviews, source: :reviewed_book
  validates :username, :email, presence: true
  validates :username, :email, uniqueness: { case_sensitive: false }
  before_validation :downcase_email
  has_secure_password

  def self.create_from_omniauth(auth)
    User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
      u.username = auth['info']['name']
      u.email = auth['info']['email']
      u.password = SecureRandom.hex(16)
    end
  end

  private
  
  def downcase_email
    self.email = self.email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include BooksHelper
  before_action :redirect_if_not_logged_in, only: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  
  def show
    @user = current_user
    @books = current_user.borrowed_books.currently_checked_out_books.select {|book| current_borrower(book) == current_user }
    @reviews = current_user.reviews
    user_from_url_submitted_id = User.find_by(id: params[:id])
    redirect_if_not_authorized_to_view(user_from_url_submitted_id)
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<br>
<h2 class="center">Sign Up to Join Our Library!</h2>
<h4 class="center">If you already have an account, please <%= link_to "log in", login_path %>.</h4>

<%= render partial: 'shared/error_display', locals: { object: @user }%>

<div class="container">
<%= form_for(@user, url: "/signup") do |f| %>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br><br>
    <%= f.label :password%><br>
    <%= f.password_field :password%><br><br>
    <%= f.submit class:"btn indigo darken-4"%>
<% end %>
</div>

app/views/users/show.html.erb
<br>
<h2 class="center"><%= @user.username %></h2>

<h5 class="center"><%= @user.email %></h5>

<% if admin? %>
    <div class="container">
        <br>
        <h5><%= link_to "All Reviews", "/admin/reviews" %></h5>
        <h5><%= link_to "Checkouts History for all Users", checkouts_path %></h5>
        <h5><%= link_to "Add a Book to the Library", new_book_path %></h5>
        <br>
    </div>
<% else %>

    <h4 class="center"><%= link_to "Checkouts History", checkouts_path %></h4>
    
    <h4 class="center">Checked-Out Books</h4>
        <div class="container">
            <% if @books.empty? %>
                <div class="center"><strong>—No books currently checked out.</strong></div>
            <% else %>
                <% @books.each do |book| %>
                    <div><h5><%= link_to book.title, book_path(book.id) %></h5>
                        <%= render partial: 'books/author_description_display', locals: { book: book } %>
                        <strong class="red-text text-darken-3"><%= book_due_date(book) %></strong>
                    </div>
                <% end %>
            <% end %>
        </div>
    
    <h4 class="center">My Book Reviews</h4>
        <div class="container">
            <% if @reviews.empty? %>
                <div class="center"><strong class="center">—No reviews currently.</strong></div>
            <% else %>
                <% @reviews.each do |review| %>
                    <div>
                        <h5><%= reviewer_username(review) %>'s Review of '<%= link_to reviewed_book_title(review), book_path(review.reviewed_book.id) %>'</h5>
                        <h6><%= link_to review.title, review_path(review.id) %></h6>
                        <%= render partial: 'reviews/review_display', locals: { review: review }%>
                    </div>
                <% end %>
            <% end %>
        </div>
    
<% end %>