config/routes.rb
Rails.application.routes.draw do

  root "static#home"

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: "user"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :books do
    resources :reviews, only: [:index, :new, :create]
    resources :checkouts, only: [:create, :update]
  end

  resources :checkouts, only: [:index]

  scope '/admin' do
    resources :reviews, only: [:index]
  end

  resources :reviews, only: [:show, :edit, :update, :destroy]

end

app/models/book.rb
class Book < ApplicationRecord
    has_many :checkouts, foreign_key: :borrowed_book_id, dependent: :destroy
    has_many :borrowers, through: :checkouts, source: :borrower
    has_many :reviews, foreign_key: :reviewed_book_id, dependent: :destroy
    has_many :reviewers, through: :reviews, source: :reviewer
    validates :authors, :title, :description, :publisher, :publication_date, :categories, :isbn, presence: true
    validates :title, uniqueness: { scope: :authors, message: "with the same author is already in our libray" }
    validate :publication_date_year_valid, if: :publication_date
    validate :isbn_conventions, if: :isbn

    def publication_date_year_valid
        if !self.publication_date.to_i || self.publication_date.length != 4
            self.errors.add(:publication_date, "must be formatted as a four-digit number")
        elsif self.publication_date.to_i > Time.now.year
            self.errors.add(:publication_date, "cannot be in the future")
        end
    end

    def isbn_conventions
        if !self.isbn.split(", ").all? {|isbn| isbn.match(/(\A\d{9}[X]\z|\A\d{10}\z|\A\d{13}\z)/) }
            self.errors.add(:isbn, "must comply with isbn conventions")
        end
    end

    def self.format_query(queries)
        submitted_queries = queries.reject { |k,v| v.empty? }
        submitted_queries[:title] = "intitle:#{submitted_queries[:title]}" if submitted_queries[:title]
        submitted_queries[:author] = "inauthor:#{submitted_queries[:author]}" if submitted_queries[:author]
        submitted_queries[:category] = "subject:#{submitted_queries[:category]}" if submitted_queries[:category]
        submitted_queries[:isbn] = "isbn:#{submitted_queries[:isbn]}" if submitted_queries[:isbn]
        formatted_search_query = submitted_queries.values.join("+")
    end

    def display_description
        !self.description.match(/[.?!]\z/) ? self.description << "." : self.description
    end

    def display_authors
        authors_array = self.authors.split(",")
        case authors_array.count
        when 1
            self.authors
        when 2
            authors_array.join(" and ")
        when 3..100
            authors_array[-1] = "and " + authors_array[-1]
            authors_array.join(", ")
        end
    end

    def self.currently_checked_out_books
        self.where(currently_checked_out: true).distinct
    end

    def aggregate_book_rating
        self.reviews.average(:rating)
    end

    def self.has_reviews
        self.all.select {|book| !book.reviews.empty? }
    end

    def self.ordered_by_aggregate_ratings
        self.has_reviews.sort_by { |book| book.aggregate_book_rating }.reverse
    end

    def self.most_recently_added
        self.order(created_at: :desc)
    end

    def self.most_recently_published
        self.order(publication_date: :desc)
    end

    def self.search_author_name(author_query)
        self.where("authors LIKE ?", "%#{author_query}%")
    end

    def self.search_title(title_query)
        self.where("title LIKE ?", "%#{title_query}%")
    end

    def self.search_description(description_query)
        self.where("description LIKE ?", "%#{description_query}%")
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include BooksHelper
  before_action :redirect_if_not_logged_in
  before_action :redirect_if_not_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_and_set_book, only: [:show, :edit, :update, :destroy]


  def new
    flash[:message] = nil
    if params[:search]
      query_for_api = Book.format_query(params[:search])
      if fetched_books = Api.fetch_books(query_for_api)
        @google_books_instance = fetched_books.first
      else
        flash[:message] = "No search results. Please try again."
        @book = Book.new
      end
    else
      @book = Book.new
    end
  end

  def create
    if params[:google_books_instance_isbn]
      search_query = "isbn:" + params[:google_books_instance_isbn].split(",").first
      @book = Api.fetch_books(search_query).first
    else
      @book = Book.new(book_params)
    end

    if @book.save
      redirect_to book_path(@book.id)
    else
      render :new
    end
  end

  def index
    flash[:message] = nil
    if !search_keys_selection.empty?
      search_results = search_filter_chaining_method(search_keys_selection)
      if !search_results.empty?
        @books = search_results
      else
        flash[:message] = "No results found for those criteria."
        @books = Book.all
      end
    else
      @books = Book.all
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:authors, :isbn, :title, :description, :publisher, :publication_date, :categories)
  end

  def find_and_set_book
    @book = Book.find_by(id: params[:id])
  end
end

app/helpers/books_helper.rb
module BooksHelper
    
    def search_keys_selection
        search_keys = ["search_author_name", "search_title", "search_description", "ordering_filter"]
        selected_keys = search_keys.select do |key|
            !params["#{key}"].blank?
        end
        search_filters_hash = {}
        selected_keys.each do |key|
            search_filters_hash[key] = params["#{key}"]
        end
        search_filters_hash
    end

    def search_filter_chaining_method(search_filters_hash)
        result = Book
        search_filters_hash.each do |key, value|
          key == "ordering_filter" ? result = result.send("#{value}") : result = result.send("#{key}", value)
        end
        result
    end
    
    def book_index_title_display
        if number = params[:number]
            tag.h1("Top #{number} Most Reviewed Books")
        else
            tag.h1("Our Library")
        end
    end

    def display_aggregate_book_rating(book)
        if book && book.aggregate_book_rating
            "#{book.aggregate_book_rating.round(2)} Average User Rating"
        end
    end

    def checkout_button_or_checked_out_status_display(book)
        if !book.currently_checked_out
            button_to "Check this book out of the library", book_checkouts_path(book.id), class: "btn indigo darken-4"
        elsif current_borrower(book) == current_user
            button_to "Return Book (#{book_due_date(book)})", book_checkout_path(book.id, current_checkout_record(book).id), method: :patch, class: "btn indigo darken-4"
        else
            tag.h4("This book is currently checked out.")
        end
    end

    def current_borrower(book)
        if book.currently_checked_out
            current_checkout_record(book).borrower
        end
    end

    def current_checkout_record(book)
        if book.currently_checked_out
            book.checkouts.order(:created_at).last
        end
    end

    def book_due_date(book)
        due_date = current_checkout_record(book).due_date
        "DUE: #{format_date(due_date)}"
    end
end

app/views/books/_author_description_display.html.erb
<p><strong>Author(s): </strong><%= book.display_authors %></p>
<p><strong>Description: </strong><%= book.display_description %></p>

app/views/books/_form.html.erb
<%= render partial: '/shared/error_display', locals: { object: book } %>

<ul>
<%= form_for book do |f| %>
    <li><%= f.label :title %>
        <%= f.text_field :title %></li>
    <li><%= f.label :authors %>
        <%= f.text_field :authors %>
        </li>
    <li><%= f.label :description %>
        <%= f.text_area :description %></li>
    <li><%= f.label :publisher %>
        <%= f.text_field :publisher %></li>
    <li><%= f.label :publication_date %>
        <%= f.text_field :publication_date %></li>
    <li><%= f.label :categories %>
        <%= f.text_field :categories %></li>
    <li><%= f.label :isbn %><span> (EX: 9781628157383, 1628157380)</span>
        <%= f.text_field :isbn %></li>
        <br>
    <li><%= f.submit class:"btn indigo darken-4"%></li>
    
<% end %>
</ul>

app/views/books/edit.html.erb
<div class="container">
<br>
<h1>Edit this Book</h1>
<%= render partial: 'form', locals: { book: @book } %>
</div>

app/views/books/index.html.erb
<br>
<div class="center">
    <%= book_index_title_display %>
    <h5>Click on any title to see more information,<br> check out the book,<br> or write a review.</h5>
</div>
    <br>
<div class="container cyan-text text-darken-1">
    <h4 class= "center">Order and Filter Books:</h4>
    <div class="container">
        <%= form_tag books_path, method: :get do %>
            <h5 class="center">SEARCH</h5><br>
                by Author: <%= text_field_tag :search_author_name %><br>
                by Title: <%= text_field_tag :search_title %><br>
                by Description: <%= text_field_tag :search_description %><br>
            <h5 class="center">ORDER</h5>
                <%= radio_button_tag :ordering_filter, :most_recently_added %>
                    <label for="ordering_filter_most_recently_added" class="cyan-text text-darken-1">by Most Recently Added</label><br>
                <%= radio_button_tag :ordering_filter, :most_recently_published %>
                    <label for="ordering_filter_most_recently_published" class="cyan-text text-darken-1">by Most Recently Published</label><br>  
                <%= radio_button_tag :ordering_filter, :ordered_by_aggregate_ratings %>
                    <label for="ordering_filter_ordered_by_aggregate_ratings" class="cyan-text text-darken-1">by Highest Rated</label><br>
                <br>
            <%= submit_tag "Filter", class:"btn cyan darken-3" %>
        <% end %>
    </div>
    <br>

    <% if admin? %>
        <div><h2><%= link_to "Add a New Book", new_book_path %></h2></div><br>
    <% end %>
</div>

<% @books.each do |book| %>
    <div class="container">
        <h5><%= link_to book.title, book_path(book.id) %></h5>
        <%= render partial: 'author_description_display', locals: { book: book } %>
    </div>
<% end %>  

app/views/books/new.html.erb
<div class="container">
    <br>
<h1 class="center">Add a New Book to the Library</h1>

<% if @google_books_instance %>
    <h3>Search Results.<br> Would like to add this book to the library?</h3>
        <%= form_for @google_books_instance do |f| %>
            <strong><%= @google_books_instance.title %></strong><br>
            
            <%= render partial: 'author_description_display', locals: { book: @google_books_instance } %>

            <input type="hidden" name="google_books_instance_isbn" value="<%=@google_books_instance.isbn%>"/>
            <%= f.submit "Add Book to Library", class:"btn indigo darken-4" %>
            
        <% end %>
    <%= button_to "Start Over?", new_book_path, method: :get, class:"btn indigo darken-4" %>

<% else %>

    <h4>Search for a New Book from Google Books</h4>
        <ul>
        <%= form_tag new_book_path, method: :get do %>
            <li>Author <br><%= text_field_tag '[search]author' %></li>
            <li>Title <br><%= text_field_tag '[search]title' %></li>
            <li>Category <br><%= text_field_tag '[search]category' %></li>
            <li>ISBN (number only) <br><%= text_field_tag '[search]isbn' %></li>
                <br>
            <li><%= submit_tag "Search", class:"btn indigo darken-4" %></li>
        <% end %>
        </ul>
    <br>
    <h4>Or Manually Add a New Book</h4>
        <%= render partial: 'form', locals: { book: @book } %>
<% end %>
</div>

app/views/books/show.html.erb
<div class="container">
    <br><br>
    <h2 class="center"><%= @book.title %></h2>
        <br>
    <h4 class="center yellow-text text-darken-3"><%= display_aggregate_book_rating(@book) %></h4>
    <h4 class="cyan-text text-darken-3">Author(s):</h4>
        <h5><%= @book.display_authors %></h5>
    <h4 class="cyan-text text-darken-3">Description:</h4>
        <h5><%= @book.display_description %></h5>
    <h4 class="cyan-text text-darken-3">Publisher:</h4>
        <h5><%= @book.publisher %></h5>
    <h4 class="cyan-text text-darken-3">Publication Date:</h4>
        <h5><%= @book.publication_date %></h5>
    <h4 class="cyan-text text-darken-3">Categories:</h4>
        <h5><%= @book.categories %></h5><br>

    <% if admin? %>
        <h5><%= link_to "Edit this Book", edit_book_path(@book.id) %></h5>
        <h5><%= link_to "Remove this Book from the Library", book_path(@book.id), method: "delete" %></h5>
    <% else  %>
        <%= checkout_button_or_checked_out_status_display(@book) %>
        <h5><%= link_to "Review this Book", new_book_review_path(@book.id) unless user_reviewed_book_already?(@book) %></h5>
    <% end %>

    <h5><%= link_to "See Reviews", book_reviews_path(@book.id) %></h5>

    <h5><%= link_to "Back to Books", books_path %></h5><br>
</div>