config/routes.rb
Rails.application.routes.draw do

  root "static#home"

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: "user"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :books do
    resources :reviews, only: [:index, :new, :create]
    resources :checkouts, only: [:create, :update]
  end

  resources :checkouts, only: [:index]

  scope '/admin' do
    resources :reviews, only: [:index]
  end

  resources :reviews, only: [:show, :edit, :update, :destroy]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include ReviewsHelper
  before_action :redirect_if_not_logged_in
  before_action :find_and_set_review, only: [:show, :edit, :update, :destroy]
  before_action :find_and_set_book, only: [:new, :create, :index]
  
  def new
    if user_reviewed_book_already?(@book)
      flash[:message] = "You have already reviewed this book."
      redirect_to book_path(@book.id)
    end
    @review = @book.reviews.build
  end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      redirect_to review_path(@review.id)
    else
      render :new
    end
  end

  def index
    if params[:book_id] && @book
      @reviews = @book.reviews
    elsif admin?
      @reviews = Review.all
    else
      flash[:message] = "That book was not found. Please select a book."
      redirect_to books_path
    end
  end

  def show
    @book = @review.reviewed_book
  end

  def edit
    if !authorized_to_edit_review?(@review)
      flash[:message] = "You are not authorized to edit that review."
      redirect_to user_path(current_user)
    end
    @book = @review.reviewed_book
  end

  def update
    if @review.update(review_params)
      redirect_to review_path(@review.id)
    else
      @book = @review.reviewed_book
      render :edit
    end
  end

  def destroy
    if authorized_to_destroy_review?(@review)
      @review.destroy
      redirect_to books_path
    else
      flash[:message] = "You are not authorized to remove that review."
      redirect_to user_path(current_user)
    end
  end

  private
    
  def review_params
      params.require(:review).permit(:title, :content, :rating, :recommend, :kid_friendly, :reviewed_book_id)
  end

  def find_and_set_review
    @review = Review.find_by(id: params[:id])
  end

  def find_and_set_book
    @book = Book.find_by(id: params[:book_id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def display_boolean_yes_no(boolean)
        boolean ? "Yes" : "No"
    end

    def review_page_title
        if params[:book_id]
            tag.h3("'#{@book.title},' reviewed by #{current_user.username}")
        else
            tag.h3("'#{@book.title},' reviewed by #{@review.reviewer.username}")
        end
    end

    def reviews_page_title
        if params[:book_id]
            tag.h2("All Reviews of '#{@book.title}'", class: "center")
        else
            tag.h2("All Reviews", class: "center")
        end
    end

    def rating_display(review)
        tag.span("Rating: ", class: "indigo-text text-lighten-2") + "#{review.rating} / 10"
    end

    def recommend_display(review)
        tag.span("Recommended? ", class: "indigo-text text-lighten-2") + display_boolean_yes_no(review.recommend)
    end
    
    def kid_friendly_display(review)
        tag.span("Kid Friendly? ", class: "indigo-text text-lighten-2") + display_boolean_yes_no(review.kid_friendly)
    end

    def reviewer_username(review)
        review.reviewer.username
    end

    def reviewed_book_title(review)
        review.reviewed_book.title
    end

    def authorized_to_edit_review?(review)
        review.reviewer == current_user
    end
    
    def authorized_to_destroy_review?(review)
        admin? || review.reviewer == current_user
    end

    def user_reviewed_book_already?(book)
        !current_user.reviews.where(reviewed_book: book).empty?
    end
end

app/views/reviews/_form.html.erb
<ul>
    <%= f.hidden_field :reviewed_book_id %>
    <li><%= f.label :title %>
    <%= f.text_field :title %></li>
    <li><%= f.label :content %>
    <%= f.text_area :content %></li>
    <li><%= f.label :rating %> (1–10)
    <%= f.number_field :rating, in: 1..10 %></li>
    <li><%= f.label :recommend %>
    <%= f.check_box :recommend %></li>
    <li><%= f.label :kid_friendly %>
        <%= f.check_box :kid_friendly %></li>
    <li><%= f.submit class:"btn indigo darken-4" %></li>
    <br>
</ul>

app/views/reviews/_review_display.html.erb
<p><span class="indigo-text text-lighten-2">Review: </span><%= review.content %></p>
<p><%= rating_display(review) %></p>
<p><%= recommend_display(review) %></p>
<p><%= kid_friendly_display(review) %></p>

app/views/reviews/edit.html.erb
<div class="container">
<br>
<h2>Edit Review</h2>
<%= review_page_title %>

<%= render partial: 'shared/error_display', locals: { object: @review }%>

<%= form_for @review, url: review_path(@review.id) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
<% end %>
</div>

app/views/reviews/index.html.erb
<div class="container">
    <br><br>
<%= reviews_page_title %>
<h4 class="center yellow-text text-darken-3"><%= display_aggregate_book_rating(@book) %></h4>
<% @reviews.each do |review| %>
    <div class="container">
        <h4><%= reviewer_username(review) %>'s Review</h4>
        <h4><%= link_to review.title, review_path(review.id) %></h4>
        <%= render partial: 'review_display', locals: { review: review }%>
    </div><br>
<% end %>

<% if !user_reviewed_book_already?(@book) && !admin? %>
<h5><%= link_to "Review this Book", new_book_review_path(@book.id) %></h5>
<% end %>

<h4 class="center"><%= link_to "Back to '#{@book.title}'", book_path(@book.id) if @book %></h4><br>
</div>

app/views/reviews/new.html.erb
<div class="container">
<br>
<h2>Add a New Review</h2>
<%= review_page_title %>

<%= render partial: 'shared/error_display', locals: { object: @review }%>

<%= form_for @review, url: book_reviews_path do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
<% end %>
</div>

app/views/reviews/show.html.erb
<div class="container">
<br>
<%= review_page_title %>
<h4 class="indigo-text text-lighten-1"><%= @review.title %></h4>
<%= render partial: 'review_display', locals: { review: @review } %>
    <br>
<h5><%= link_to "Edit this Review", edit_review_path(@review.id) if authorized_to_edit_review?(@review) %></h5>

<%= form_tag("/reviews/#{@review.id}", method: "delete") do %>
    <%= submit_tag "Delete this Review", class:"btn indigo darken-4" %>
<% end if authorized_to_destroy_review?(@review) %>

<h5><%= link_to "See All Reviews of This Book", book_reviews_path(@book.id) %></h5>
<br>
</div>

app/views/reviews/showedit.html.erb
<h1>Reviews#showedit</h1>
<p>Find me in app/views/reviews/showedit.html.erb</p>