config/routes.rb
Rails.application.routes.draw do

  root "static#home"

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: "user"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :books do
    resources :reviews, only: [:index, :new, :create]
    resources :checkouts, only: [:create, :update]
  end

  resources :checkouts, only: [:index]

  scope '/admin' do
    resources :reviews, only: [:index]
  end

  resources :reviews, only: [:show, :edit, :update, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksAndBanter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body style="background: url(https://i.imgur.com/Q1QLHhj.jpeg)" title="old library background Book of Kells library of Trinity College Dublin">
  <header>
    <nav class="indigo darken-4">
      <div class="container">
        <ul>
          <% if logged_in? %>
            <li><%= link_to "Our Library's Books", books_path %></li>
            <li><%= link_to "My Account Page", user_path(current_user) %></li>
            <li><%= link_to "Log Out", '/logout', method: 'delete' %></li>
          <% else %>
            <li><%= button_to "Log In With Google", '/auth/google_oauth2', class:"btn cyan darken-3" %></li>
          <% end %>
          <div class="right">
            <% if logged_in? %>
              <li>You are logged in as "<%= current_user.username %>."</li>
            <% end %>
          </div>
        </ul>
      </div>
    </nav>
  </header>

  <main>
    <div class="container grey-text text-lighten-1" id="text_container">
  
      <% if flash[:message] %>
        <div id="error_explanation"><h4 class="center"><%= flash[:message] %></h4></div>
      <% end %>

      <%= yield %>
        
        <br>
    </div>
  </main>
        <footer class="page-footer indigo darken-4">
          <div class="container center">
              <p>&copy; 2021 <strong>Books & Banter</strong></p>
          </div>
        </footer>
  </body>
  
</html>